### ISSUE TITLE
ブラッシュアッププロジェクト

### ISSUE THREAD

**Issue by awn-git** [awn-git/Abrowzer#23]
## 概要
ブラッシュアッププロジェクトにて行うタスクなどを把握するためのissueです。
タスクと書いてみたものの、やりたいことなんかも書いてしまおう:confused:

## タスク一覧(とりあえずジャンルとか色々無視して列挙)
 - [ ] タスクを洗い出す
 - [ ] manifest.jsonのプロパティを見直す
 - [x] manifest.jsonの`  "version": "1.0.0",`の書き方を検討する (ref: https://github.com/awn-git/Abrowzer/commit/91388d8c31b161c6d85bdbd7255d5e216f23f28b )
 - [ ] read.cgiにてimgur画像を投稿した際に表示される「削除用URL」を履歴として保管したい (ref: https://github.com/awn-git/Abrowzer/issues/24 )
 - [x] 履歴作成を止めるボタンを実装したい (ref: https://github.com/awn-git/Abrowzer/issues/25 , https://github.com/awn-git/Abrowzer/commit/073cd31ad8c4b1c6aee408bae4bc25f97be8918c )
 - [ ] 履歴を見やすくしたい
 - [ ] スレッド一覧(subject, subback)を色々ソートしたい (ref: https://github.com/awn-git/Abrowzer/issues/26 )
 - [x] コンテキストメニューのロードを、おーぷん２ちゃんねるにアクセス前に行いたい (ref: https://github.com/awn-git/Abrowzer/commit/44f42cb9315c37573c7e3396c3776b4b7ca55ffe )
 - [ ] user css のフォルダやら配置場所やらを整理したい
 - [ ] テンプレを保存する何かをdashboardに付けたい (ref: #27 )
 - [ ] AAfont的なものをどうするか検討する
 - [ ] background.jsのinjecctなんちゃら関数周りの整備
 - [ ] dashboard.jsの整備(特にevent listenしている関数。もう少し綺麗になるはず)
 - [ ] User-AgentってやっぱりMonazillaなんちゃらにすべきなのか？ 
 - [ ] CSSのデフォルトの値を確定したい
 - [ ] テストをどうすればいいのかなんとかしよう:confused:
 - [x] Abrowzerのアイコンを作る:confused: (ref: https://github.com/awn-git/Abrowzer/commit/91388d8c31b161c6d85bdbd7255d5e216f23f28b )
 - [ ] develop_frozen2016xxxx的なbranchを作りたい
 - [ ] コンテキストメニューの見直し (ref: #28 )
 - [ ] 履歴の永続化はchrome.storage.localではなく、Indexed Databaseにしたい。 (ref: #33 )
 - [ ] inspectwepage(content_scripts)の見直し (ref: #32 )

### ネタに困ったら・・・
 - [open2chの運営スレ](http://open.open2ch.net/open2ch/)の要望や質問スレを見る
 - 他の専ブラさんのissueやユーザレビューなどを見る

### 書き込みが吸い込まれる現象への対策として、
 - imgur削除URL取得と同じ仕組みで書き込み直前で{名前欄,メール欄,本文}をdashboard.jsに送信
 - (書き込みに失敗しても成功しても)直前に投稿した内容を
 - コンテキストメニューからキックして貼り付け可能にする

という案

### 【超漠然】データのロード＆アンロード
 - アプリケーションの外へデータを出す
 - アプリケーションの中へデータをロードする

なんらかの形で実現したい。CSVで閲覧スレ履歴をimport/exportできるとか。
でもそうするとFILE APIを駆使しないといけない。:confused:
